# Generated by Django 5.2.1 on 2025-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='user',
            name='self_message',
            field=models.TextField(blank=True, default='', verbose_name='自我展示'),
        ),
    ]
