# Generated by Django 5.2.1 on 2025-05-31 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_class_name_user_college_user_self_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='class_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.class', verbose_name='所属班级'),
        ),
    ]
